import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { mkdtemp, mkdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import {
  ExtractionService,
  isGeneratedContent,
  isGeneratedPath,
  isGoTestPath,
} from "../src/index.js";

const GENERATED_HEADER = "// Code generated by conversion-gen. DO NOT EDIT.\n";

/** A repository holding one hand-written file plus a spread of skippable ones. */
async function corpus(): Promise<string> {
  const root = await mkdtemp(join(tmpdir(), "flashlearn-scale-"));
  await mkdir(join(root, "pkg", "kubelet"), { recursive: true });
  await mkdir(join(root, "pkg", "apis"), { recursive: true });
  await mkdir(join(root, "CHANGELOG"), { recursive: true });

  await writeFile(
    join(root, "pkg", "kubelet", "kubelet.go"),
    "// Run starts the kubelet main loop.\nfunc Run() {}\n",
  );
  await writeFile(join(root, "pkg", "kubelet", "kubelet_test.go"), "// TestRun checks Run.\nfunc TestRun() {}\n");
  await writeFile(
    join(root, "pkg", "apis", "zz_generated.conversion.go"),
    "// Convert does things.\nfunc Convert() {}\n",
  );
  await writeFile(join(root, "pkg", "apis", "api.pb.go"), "// Marshal serializes.\nfunc Marshal() {}\n");
  await writeFile(
    join(root, "pkg", "apis", "types.go"),
    `${GENERATED_HEADER}\n// Spec describes a pod.\ntype Spec struct{}\n`,
  );
  await writeFile(join(root, "CHANGELOG", "CHANGELOG-1.6.md"), "# v1.6.0\nRelease notes.\n");
  await writeFile(join(root, "notes.md"), "# Overview\nExplains the project.\n");
  return root;
}

test("classifies generated, changelog, and test paths", () => {
  for (const path of [
    "pkg/apis/zz_generated.conversion.go",
    "pkg/apis/api.pb.go",
    "pkg/apis/types_generated.go",
    "pkg/bindata.go",
    "CHANGELOG/CHANGELOG-1.6.md",
  ]) {
    assert.equal(isGeneratedPath(path), true, `expected ${path} to be skipped`);
  }

  for (const path of ["pkg/kubelet/kubelet.go", "docs/notes.md", "src/a.ts"]) {
    assert.equal(isGeneratedPath(path), false, `expected ${path} to be kept`);
  }

  assert.equal(isGoTestPath("pkg/kubelet/kubelet_test.go"), true);
  assert.equal(isGoTestPath("pkg/kubelet/kubelet.go"), false);
});

test("detects the generated marker only as a whole line", () => {
  assert.equal(isGeneratedContent(GENERATED_HEADER), true);
  assert.equal(
    isGeneratedContent("package main\n\n// Code generated by hand. DO NOT EDIT.\nfunc A() {}\n"),
    true,
    "the marker is recognized anywhere in the sniffed head",
  );
  assert.equal(
    isGeneratedContent("// This file explains how Code generated by X. DO NOT EDIT. works inline.\n"),
    false,
    "prose mentioning the phrase mid-line is not a marker",
  );
});

test("scanRepository skips generated, test, and changelog files", async (t) => {
  const root = await corpus();
  t.after(async () => rm(root, { recursive: true, force: true }));

  const documents = await new ExtractionService().scanRepository(root);

  assert.deepEqual(documents.map((document) => document.path), ["notes.md", "pkg/kubelet/kubelet.go"]);
});

test("a file is skipped by its generated marker even when the name looks ordinary", async (t) => {
  const root = await corpus();
  t.after(async () => rm(root, { recursive: true, force: true }));

  const documents = await new ExtractionService().scanRepository(root);

  assert.equal(
    documents.some((document) => document.path === "pkg/apis/types.go"),
    false,
    "content sniffing catches generators that do not follow a filename pattern",
  );
});

test("subpath scopes the run and preserves repository-relative attribution", async (t) => {
  const root = await corpus();
  t.after(async () => rm(root, { recursive: true, force: true }));
  execFileSync("git", ["init", "-q", "-b", "main"], { cwd: root });
  execFileSync("git", ["config", "user.email", "t@example.com"], { cwd: root });
  execFileSync("git", ["config", "user.name", "T"], { cwd: root });
  execFileSync("git", ["add", "-A"], { cwd: root });
  execFileSync("git", ["commit", "-q", "-m", "seed"], { cwd: root });

  const cards = await new ExtractionService().generateFromRepository(root, { subpath: "pkg/kubelet" });

  assert.ok(cards.length > 0, "the scoped folder still yields cards");
  for (const card of cards) {
    assert.equal(
      card.source.path,
      "pkg/kubelet/kubelet.go",
      "scoping must not rewrite attribution to be relative to the subpath",
    );
    assert.match(card.source.sha, /^[0-9a-f]{40}$/, "a real blob sha still resolves when scoped");
  }
});

test("subpath accepts a leading ./ and rejects escaping the repository", async (t) => {
  const root = await corpus();
  t.after(async () => rm(root, { recursive: true, force: true }));
  const service = new ExtractionService();

  const documents = await service.scanRepository(root, { subpath: "./pkg/kubelet" });
  assert.deepEqual(documents.map((document) => document.path), ["pkg/kubelet/kubelet.go"]);

  await assert.rejects(
    async () => service.scanRepository(root, { subpath: "../outside" }),
    /stay inside the repository/,
  );
});

test("maxFiles caps how many documents a run reads", async (t) => {
  const root = await corpus();
  t.after(async () => rm(root, { recursive: true, force: true }));

  const documents = await new ExtractionService().scanRepository(root, { maxFiles: 1 });

  assert.equal(documents.length, 1);
});

test("hand-written Go still produces its doc-comment card", async (t) => {
  const root = await corpus();
  t.after(async () => rm(root, { recursive: true, force: true }));

  const cards = await new ExtractionService().generateFromRepository(root, { subpath: "pkg/kubelet" });

  assert.deepEqual(cards.map((card) => card.question), ["What does `Run()` do?"]);
  assert.equal(cards[0]?.answer, "Run starts the kubelet main loop.");
});
